### PR TITLE
Injecting the ToC into Yao docs

### PR DESCRIPTION
**Pull request by VarLad**

### CODE REVIEW

**Comment by Roger-luo** [comment]
This looks good in general, but the layout is a bit strange - can we have both the sidebar and Toc centerized instead of only centerize the content?

**Comment by VarLad** [comment]
Isn't it already centralized?
I just removed the numbers and the scroll line though

Look here again https://varlad.github.io/Yao.jl/dev/man/base.html

**Comment by VarLad** [comment]
Also, sorry for the late response, strange that Github didn't notify me.... :sweat_smile:

**Comment by Roger-luo** [comment]
Yeah this does look better, I think I'll just merge this for now. The right TOC bar still looks a bit strange to me, perhaps it's because of the position. But we can improve this later.

**Comment by VarLad** [comment]
I think it looks strange because the ToC at the left is not centralized

So.... maybe we should place the ToC in the right to far right too?

Screenshot from 2021-06-29 13-45-07

**Comment by VarLad** [comment]
Opinions are welcome
Github is not notifying me about any of this so thats strange....

Again, sorry for the late response :sweat_smile:

**Comment by VarLad** [comment]
........Google was marking all my github notifications as Spam.... :rofl:

**Pull request merged**
