### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by cbwang2016**

### CODE REVIEW

**Comment by Roger-luo** [comment]
Hi @cbwang2016, thanks for the PR, we polished some APIs in latest v0.4, and nshot is corrected to nshots for "number of shots"

**Comment by cbwang2016** [comment]
@Roger-luo but my version is 0.4.1

**Comment by Roger-luo** [comment]
Please make sure you have updated your package with `up` in pkg mode.

**Comment by Roger-luo** [comment]
Can you show me your `status`?

**Comment by cbwang2016** [comment]
```
(v1.1) pkg> status
    Status `C:\Users\HP\.julia\environments\v1.1\Project.toml`
  [c52e3926] Atom v0.8.5
  [e5e0dc1b] Juno v0.7.0
  [91a5bcdd] Plots v0.24.0
  [d330b81b] PyPlot v2.8.1
  [5872b779] Yao v0.4.1
```
```
julia> measure(zero_state(4);nshot=6)
6-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0

julia> measure(zero_state(4);nshots=6)
ERROR: MethodError: no method matching measure(::DefaultRegister{1,Complex{Float64},Array{Complex{Float64},2}}; nshots=6)
Closest candidates are:
  measure(::AbstractRegister{1,T} where T; nshot) at C:\Users\HP\.julia\packages\Yao\q6Bty\src\Registers\measure.jl:19 got unsupported keyword argument
"nshots"
  measure(::AbstractRegister{B,T} where T; nshot) where B at C:\Users\HP\.julia\packages\Yao\q6Bty\src\Registers\measure.jl:21 got unsupported keyword argument "nshots"
  measure(::AbstractRegister, ::Any; args...) at C:\Users\HP\.julia\packages\Yao\q6Bty\src\Registers\measure.jl:78
Stacktrace:
 [1] kwerr(::NamedTuple{(:nshots,),Tuple{Int64}}, ::Function, ::DefaultRegister{1,Complex{Float64},Array{Complex{Float64},2}}) at .\error.jl:125
 [2] (::getfield(Yao.Registers, Symbol("#kw##measure")))(::NamedTuple{(:nshots,),Tuple{Int64}}, ::typeof(measure), ::DefaultRegister{1,Complex{Float64},Array{Complex{Float64},2}}) at .\none:0
 [3] top-level scope at none:0

```

**Comment by Roger-luo** [comment]
@cbwang2016 you are using v0.3.x somehow. This might because you updated after you `using` the module.

Try the following solution:

1. rm Yao

```
pkg> rm Yao
```

2. delete cache

```
pkg> gc
```

3. install it back

```
pkg> add Yao
```

remember to exit REPL and `using Yao` again, if you don't exit, since the module is already loaded into memory, nothing will change.

**Comment by Roger-luo** [comment]
I'll close this since it seems not to be the correct update to docs. But feel free to let me know if this works for you. And you can also ask questions directly in julia slack in #yao-dev channel.

**Pull request closed without merging**
